# Generated by Django 5.1.5 on 2025-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_redes_imagenproyecto_sobremi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redes',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='redes'),
        ),
    ]
