# Generated by Django 5.1.5 on 2025-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_alter_sobremi_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redes',
            name='icono',
        ),
        migrations.AddField(
            model_name='redes',
            name='icono_bootstrap',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono (Bootstrap Class)'),
        ),
    ]
