# Generated by Django 5.1.5 on 2025-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_alter_redes_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobremi',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sobre_mi'),
        ),
    ]
